#!/bin/bash
# UUID from disk where the backup will be done
BACKUP_UUID_DISK="5c12ace1-9d3d-4bcf-83bd-a3a2629e71ee"

# Directories being ignored split by ;
EXCLUSIONS="/autofs/;/home/grey/pCloudDrive/;/dev/;/proc/;/sys/;/tmp/;/run/;/mnt/;/media/;/lost+found/"

# Backup creation frequency (cron format)
BACKUP_FREQUENCY="0 0 * * *"

# Number of days until a backup is removed
REMOVE_BACKUPS_OLDERS="30"
